### ISSUE TITLE
waiting.gif missing

### ISSUE THREAD

**Issue by pirj** [evancz/elm-architecture-tutorial#100]
In `05-http.elm` getting this:

    Failed to load resource: the server responded with a status of 404 (Not Found), http://localhost:8000/examples/waiting.gif

Didn't want to send a PR with a randomly picked up gif from the net, should I?

**Comment by evancz** [comment]
The latest versions of the HTTP examples no longer use a loading image:

- https://github.com/evancz/elm-architecture-tutorial/blob/master/examples/05-http.elm
- https://github.com/evancz/elm-architecture-tutorial/blob/master/examples/06-json.elm
