### ISSUE TITLE
Error in tutorial text code example

### ISSUE THREAD

**Issue by BryanJBryce** [evancz/elm-architecture-tutorial#105]
I'm not sure if this is the right place to leave this, if the actual tutorial text was hosted I'd comment there, but the tutorial text has either a misleading or incorrect code example from 05-Http: 

```
decodeGifUrl : Json.Decoder String
decodeGifUrl =
  Json.at ["data", "image_url"] Json.string
```

In order to match the accompanying code in this repo and in the online example:
`Json.Decoder` should be `Decode.Decoder`
`Json.at` should be `Decode.at`
`Json.string` should be `Decode.String`

**Comment by evancz** [comment]
The examples have been updated as new releases come out. It looks like the JSON example code matches exactly in the latest version. Sorry for the trouble with the older version!
