### ISSUE TITLE
No mention of foldp?

### ISSUE THREAD

**Issue by BethAr** [evancz/elm-architecture-tutorial#11]
I just noticed that the tutorial has been updated and there is no mention of foldp at all. I don't think a beginner can understand how things are being achieved without it. The startApp makes it tantamount to magic.

**Comment by evancz** [comment]
So far, the beginners do not agree with you. The point is to delay concepts for as long as possible. The more gradual the learning curve, the more likely people are to make it up that curve. So I'm gonna stick with this way for now.
