### ISSUE TITLE
Counters examples

### ISSUE THREAD

**Issue by PetrSnobelt** [evancz/elm-architecture-tutorial#110]
Hello, 
some time ago I read Interesting sample/tutorial with Counter and List of Counters, but I can't find it anymore. Is there any reason why it is removed? Is there another such advanced example?

Thanks
Petr

**Comment by evancz** [comment]
The examples generally match https://guide.elm-lang.org/ these days. The content there has been updated many times as we found ways to present things better. I believe the "list of counters" example ended up being confusing for a lot of people.

Many people coming to Elm are used to thinking in terms of "components" so the guide has been adjusted to put a lot more emphasis on reaching for functions first. We found that those old examples (1) made people feel like they could bring their habits over directly from React and (2) those people were then disappointed when those habits led to difficult code, code that someone coming from a functional background would have never thought to write. In other words, the guide was not teaching them some important fundamentals of coding in a functional language.
