### ISSUE TITLE
major bug

### ISSUE THREAD

**Issue by mbr84** [evancz/elm-architecture-tutorial#115]
came here. no flow chart. followed link to the official guide's section on the 'elm architecture.' no flow chart. wtf? wtf are the flow charts?

**Comment by evancz** [comment]
I'm afraid I do not understand what you are talking about exactly.

A flow chart of what? Where were you expecting this chart? What information will it convey to you?

It seems there are no concrete actions based on the title or original post, so I will close. We should continue discussion here though, and open a new issue if this can be refined.
