### ISSUE TITLE
01-button.elm has syntax errors

### ISSUE THREAD

**Issue by vlvagerviwager** [evancz/elm-architecture-tutorial#116]
When I try to compile the [Buttons](https://github.com/evancz/elm-architecture-tutorial/blob/master/examples/01-button.elm) example, I get this:

```
$ sudo elm-make Buttons.elm --output=Buttons.html
-- SYNTAX PROBLEM -------------------------------------------------- Buttons.elm

The = operator is reserved for defining variables. Maybe you want == instead? Or
maybe you are defining a variable, but there is whitespace before it?

32|       model = 0
                ^
Maybe <http://elm-lang.org/docs/syntax> can help you figure it out.

Detected errors in 1 module.                                        
```

When I open the example in the [online editor](http://elm-lang.org/examples/buttons), it's different and compiles. Maybe the example on the [page](https://guide.elm-lang.org/architecture/user_input/buttons.html) is not intended to be copied verbatim and compiled?

Apologies if I am misunderstanding something, I am a complete Elm beginner.

- OS: macOS Sierra 10.12.4
- Elm version: 0.18.0

**Comment by 50kudos** [comment]
@zky829 Could you post and point to the actual code (the one on your machine)? It'd be obvious if we see the copied code. The error message is obvious though.

**Comment by sr-ix** [comment]
I am assuming you are doing the exercise in the Elm Guide to implement "Reset". You are attempting to redefine the value of model.

Try this instead:

```
...
    Reset ->
      model - model
```

**Comment by MikeTschudi** [comment]
Also works:

```
...
    Reset ->
      0
```

**Comment by evancz** [comment]
It looks like @sr-ix has a good theory of the root cause here. The example works for me, so I am not able to reproduce with the information here.
