### ISSUE TITLE
HTTP tutorial doesn't make it clear how load additional http library

### ISSUE THREAD

**Issue by sturad** [evancz/elm-architecture-tutorial#123]
I am not clear on how to get a new dependency elm-lang/http  loaded by elm-reactor and the tutorial doesn't mention workflow to do so. 

I see related platform issue  https://github.com/elm-lang/elm-platform/issues/162 "Error Installing The Elm HTTP Library"  I had the same issue with Elm 0.18 and the tutorial at https://guide.elm-lang.org/architecture/effects/http.html.  I threw away ~/.elm to no avail, but got it to work running 
`elm-package install elm-lang/http`

Perhaps this is normal, but I'm not sure the tutorials makes it clear when elm-reactor won't grab a dependency.  Thanks.

**Comment by evancz** [comment]
With the latest version of https://guide.elm-lang.org/ there is an `Edit` button for each example, that takes you to the online editor, like [this](https://elm-lang.org/examples/cat-gifs). So you wouldn't need to use `elm install` for that path.

This repo also has all the necessary dependencies listed in [`elm.json`](https://github.com/evancz/elm-architecture-tutorial/blob/master/elm.json), so running based on the examples in `README.md` should be working.

Finally, the guide now has a section (on [this page](https://guide.elm-lang.org/effects/)) that introduces how to use `elm install` explicitly.

So hopefully these changes address the root issue here!
