### ISSUE TITLE
?debug parameter won't work

### ISSUE THREAD

**Issue by zigomir** [evancz/elm-architecture-tutorial#13]
First example can be viewed on `http://localhost:8000/Counter.elm` for me, but navigating to `http://localhost:8000/Counter.elm?debug` will return this to me

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Uncaught TypeError: Elm.fullscreenDebug is not a function
```

Do I need to install something else? I'm running this with `Elm Reactor 0.3.1 (Elm Platform 0.15)`.

I'm opening this issue because README.md of this repository is linking to `http://localhost:8000/Counter.elm?debug`.

**Comment by InkSpeck** [comment]
Can confirm... It looks like the debug script isn't included in the html file...? which I don't believe exists in this tutorial but then again I don't know how to elm yet...
<script type="text/javascript" src="/_reactor/debug.js"></script>

**Comment by bbugh** [comment]
This was happening to me as well, and then I tried it a couple of minutes later and it was suddenly working. It was giving me some kind of error about downloading packages, so maybe elm-reactor was silently updating some packages in the background?

**Comment by netaisllc** [comment]
I also experienced this behavior (see #35) and is was the result of not properly including the location of the Reactor files.  I use Linux, installing node/npm via **nvm** so I had to set the  ELM_HOME env var correctly.

It seems that elm-reactor injects files into the project at run time and sources these files from ELM_HOME, but I could easily be wrong about that.

**Comment by AdrianoFerrari** [comment]
Same issue here, and setting ELM_HOME environment variable fixed the problem.

**Comment by evancz** [comment]
It looks like this is the same ELM_HOME issue as reported to the folks who created the npm installer so I am going to close it here.
