### ISSUE TITLE
json cat gif example broken 

### ISSUE THREAD

**Issue by niccolox** [evancz/elm-architecture-tutorial#135]
hi

the json example is broken

1. the api key is rate limited
2. the gliphy api has changed structure, the image urls are nested deeper

I'll try to post a fix, but heads up there is a docs example issue

thanks

**Comment by niccolox** [comment]
cancel that, all I needed was a new key

**Comment by dgollahon** [comment]
When I tried to do the tutorial, I had the same problem. IIRC, it was not obvious from the error message in the example this was the problem.

I think this issue should still be open and maybe the guide can be updated to advise the user that they will need an API key, get the gifs from another source where this won't be a problem, improve the error message so it tells you the full error and what you can do about it, or possibly have the key automatically refreshed periodically.
