### ISSUE TITLE
Compatibility with Elm 0.19.1

### ISSUE THREAD

**Issue by Corvince** [evancz/elm-architecture-tutorial#137]
Coming back to Elm after I read about the 0.19.1 release I discovered that this tutorial doesn't work anymore (to be specific: It is not sufficient to change the elm version from 0.19.0 to 0.19.1 in `elm.json`)

There seem to be (at least) two issues:
1) The Capital Names naming convention forbids the tutorial files to start with a number. 
2) Module names missing in the tutorial files (e.g. `module Button exposing (..)` )

I would be happy to submit a PR, but I am unsure how to solve the first issue while preserving the ordering of the files. `Tutorial-01-Button.elm` is already a bit ugly and does not work and `Tutorial01Button.elm` works, but is super ugly.

**Comment by evancz** [comment]
I made some changes such that the instructions work again with the old names. Sorry for the trouble!
