### ISSUE TITLE
Installer error - unable to open registry key

### ISSUE THREAD

**Issue by peterennis** [evancz/elm-architecture-tutorial#15]
Win 7 x64
Using Elm-Platform-0.15.exe from the link on the Elm Atchitecture tutorial page.

![capture5](https://cloud.githubusercontent.com/assets/140737/8398136/775771f0-1d98-11e5-9303-428dd91c42e7.PNG)

**Comment by peterennis** [comment]
Tested also on Windows 8.1 x32 with no error.

**Comment by evancz** [comment]
My guess is that you did not have admin privileges when you tried it the first time, so it wasn't letting you edit a certain environment variable. It looks like you got it working though. If things are still messed up, please open an issue on the elm-platform repo describing more of your situation!
