### ISSUE TITLE
Is "example 5" ("One last pattern") described somewhere ?

### ISSUE THREAD

**Issue by phtrivier** [evancz/elm-architecture-tutorial#16]
Just wanted to known if the pattern alluded to http://elm-lang.org/guide/architecture#one-last-pattern is described somewhere else ? Or if some application uses it in the context of (ooooh the FAQ) making ajax queries when someone clicks somewhere ? 

Or does the pattern get *much* more complicated when trying to add Tasks ?

**Comment by evancz** [comment]
I am right now in the process of writing up "5 through 8" of this tutorial that goes into exactly these questions. So sit tight for a week or two and I'll be ready to share!

**Comment by phtrivier** [comment]
Great news ! Thanks.
