### ISSUE TITLE
Document how AJAX (more generally, Tasks) fits in The Elm Architecture

### ISSUE THREAD

**Issue by roganov** [evancz/elm-architecture-tutorial#17]
Since Ajax is a crucial aspect of every modern website, I really believe this should be documented.
There are some examples like [zip codes](http://elm-lang.org/examples/zip-codes) and [flickr](http://elm-lang.org/examples/flickr), but the architecture these examples use is different as there is no `Model`.

**Comment by evancz** [comment]
Just added examples 5 through 8 which get into how that stuff works!

Sorry it took a while, was trying to design a coherent API and story of how this all fits together!

**Comment by roganov** [comment]
Thanks!

**Comment by evancz** [comment]
No problem! Hope it helps you make something cool :)
