### ISSUE TITLE
Example 5 does not show any gifs on Iceweasel (Firefox) 31.8 Linux 

### ISSUE THREAD

**Issue by rzetterberg** [evancz/elm-architecture-tutorial#21]
# Description

When viewing the demo at http://evancz.github.io/elm-architecture-tutorial/examples/5.html
there are no gifs shown in Firefox. I tried clicking the button multiple times, nothing happens. 

**UPDATE:** I tried disabling my browser add-ons, but that didn't have any effect.
**UPDATE 2:** I tried the project locally on my machine and it I can confirm that the view function is run and that a new URL is given each time I click the button. The problem is actually that none of the background styles are applied to the element. 
**UPDATE 3:** PR #22 should fix this problem. 

# My setup

**OS:** Debian Jessie 64-bit
**Browser:** Iceweasel (Firefox) 31.8.0
**Active add-ons:** Adblock Edge 2.1.9, Ghostery 5.4.6, Youtube All HTML5 3.0.0

# Debugging clues

## The div-container for the images is empty

This container never changes, I tried clicking the button multiple times. 

![Empty div](http://i.imgur.com/MzmCC28.png) 

## No javascript errors

![No javascript errors](http://i.imgur.com/kG7dI4b.png)

## The giphy API is loaded successfully

![API loaded successfully](http://i.imgur.com/cQNORxD.png)

**Comment by evancz** [comment]
Makes sense to just follow in the PR I think. Thanks for the thorough issue!
