### ISSUE TITLE
Example 2: invalid assertions

### ISSUE THREAD

**Issue by masklinn** [evancz/elm-architecture-tutorial#28]
Example 2 assumes and asserts that the `Counter` example 1 "encapsulated all implementation details" and provides an `init`, an `update` and a `view` function.

Example 1 doesn't provide an `init` function, neither in the explanatory text nor [in the actual code](https://github.com/evancz/elm-architecture-tutorial/blob/master/examples/1/Counter.elm)

**Comment by walkermatt** [comment]
@evancz I also found this a little confusing, I'd be happy to prepare a pull request to make the code and README consistent.

What do you think is best, adding an `init` function to Counter.elm in Example 1 or remove `init` from 2, 3 and 4? I'm very new to Elm but I think removing `init` from 2, 3 and 4 and instead simply passing an `Int` makes things easier to follow as it's explicit that the `Int` is the `Model` for the counter. Happy to be guided though.

**Comment by evancz** [comment]
Should not have things like this in http://guide.elm-lang.org/ where the tutorial lives now
