### ISSUE TITLE
Mixed content error on example 5, 6 and 7

### ISSUE THREAD

**Issue by pdamoc** [evancz/elm-architecture-tutorial#29]
When the demos are loaded through a `https` connection, as it is the case of the links from the [README.md](https://github.com/evancz/elm-architecture-tutorial/blob/master/examples/5/README.md) of each individual demo, a `Mixed Content` error is triggered by the fact that the images are fetched through a `http` connection. 

This error is reported only in the Console and the examples appear to not work.

Are there any issues/limitations of using `https` for the giphy API?

**Comment by evancz** [comment]
Not that I know of. I'll switch it to the way that uses the right kind of connection.
