### ISSUE TITLE
One child depends on another within parent.

### ISSUE THREAD

**Issue by sindikat** [evancz/elm-architecture-tutorial#30]
Suppose I have 2 components. They are implemented exactly the same. However the contents of the 2nd depends on the content of the 1st. The component consists of a `<select>` tag, an `<input>` tag, a `<button>`. User enters a string into `<input>`, presses the button, and the string appears in the `<select>`. What does it mean for the 2nd component to depend on the 1st?

Suppose the 1st component, on the left pane, denotes people. Suppose the 2nd component, on the right pane, denotes preferred actions *per* person. Suppose there are 2 people, "Wife" and "Husband". Suppose "Wife" prefers "Bach" and "Mozart", while "Husband" prefers "Stravinsky" and "Rachmaninoff".

At the beginning of program, the `<select>` tags are blank. I add "Wife" to the people pane, then add "Bach" and "Mozart" to the action pane. *Now, here's the problem!* If I add "Husband" and select it, the 2nd `<select>` tag should become empty, so that I can add "Stravinsky" and "Rachmaninoff". And every time I switch between "Wife" and "Husband" in the left pane, the list of option in the right pane should change, depending which person I've chosen.

These 2 components are implemented exactly the same with the exception of this dependency. So their are akin to Counters, while the parent GUI component, that contains both of them, is akin to CounterPair. But Elm Architecture Tutorial doesn't consider, if one counter somehow depends on another. For example, if pressing <kbd>+</kbd> on one counter would somehow influence the number on another counter, and this change would be *preserved* throughout the run.

So, for the example above, the actual data might be `type alias Model = { players : List String, actions : Dict String (List String) }`, where `actions` might be something like `Dict.fromList [("Wife", ["Bach", "Mozart"]), ("Husband", ["Stravinsky", "Rachmaninoff"])]`.

But child models can only be something like `type alias Model = { options : List String, selected : Maybe Int, inputField : String }`. Children may not know about the full data about all players and actions, they are only given list of options from their parents somehow.

Not only children must receive data from parents, they also send data back to parents somehow. When left pane switches person from "Wife" to "Husband", parents must somehow know about this, so that it can send a list of new actions to the right pane.

This question arose in [Elm Architecture: State vs Model @ elm-discuss](https://groups.google.com/d/topic/elm-discuss/xrmWjVobMcA/discussion), where you can find more ideas and discussions on the topic. The canonical solution (maybe in forms of one counter depending on another) would be a great thing to have in the Elm Architecture Tutorial, as I am not the only one, who came up with the question.

**Comment by seanhess** [comment]
@sindikat I can answer the question about displaying data. If you follow the State vs Props idea in that thread, you look up the correct options to pass in your view function:

```
    type alias ChildProps = { options : List String }
    type alias ChildState = { selected : Maybe Int, inputField : String }
    type alias ParentModel = { players : List String, actions : Dict String (List String), currentPlayer : String, childState : ChildState }

    parentView address model = 
       let options = Maybe.withDefault [] (Dict.get model.currentPlayer model.actions) in
       div [] [ Child.view { options = options } model.childState ]
```

*However*, I came here to ask about passing data back to parents. I'm running into it over and over again, any time I want to create generic components. Especially when I need to manipulate my own state, and also report something back to the parent, as the result of one user action. 

Should we make a separate issue for that? I really need feedback from someone more experienced on this.

**Comment by evancz** [comment]
@seanhess, you can use a tuple for that.

```elm
update : Action -> Model -> (Model, MessageForParent)
```

If you need effects too, you can have them the same way.

```elm
update : Action -> Model -> (Model, MessageForParent, Effects Action)
```

It's the same idea whether we are passing up an effect or any other value.

**Comment by evancz** [comment]
Maybe I took the extra generic types out of the tutorial when I added examples 5 through 8. The very generic version of things is:

```elm
update : UpdateContext -> Action -> Model -> (Model, whatever)

view : ViewContext -> Address Action -> Model -> Html
```

You don't have to follow this like a law, it's just for illustration. With `update` you can demand that the caller gives you some "context" that you do not own. So the parent can give any relevant info. Same with the `view`, you can demand info from the parent.

Then you can give info back to the parent in the return type of `update`. Whatever it is you want them to know about, just pass it out to them.

**Comment by seanhess** [comment]
@evancz thanks so much for chiming in! I had started doing it this way but I wasn't sure if I was way off in the weeds or not. This is very useful, thank you.

**Comment by aft-luke** [comment]
This makes more sense. The 'context' example was very confusing to me in the tutorial.

In my beginner brain I really *want* to be able to respond to a child's actions from inside a parent without having to change the child implementation, if that's possible...

I imagine something like this, but I can't get it past the compiler. When you run into a particular child action, do some special behavior, otherwise "fallthrough" and let the child update itself just as it normally would:

```elm
-- parent
update: Action -> Model -> Model
update act model =
    case act of
        ChildAction msg ->
            case msg of 
                ChildAction.Something someChildVal ->
                    { model | parentValue = manipulate someChildVal }
                ChildAction.AnotherThing ->
                    ...
                _ ->
                    { model | child = Child.update msg model.child }

        ParentAction ->
            ...
``` 

Not really sure why this doesn't work, but I expect its because my signature would have to be something more like `Action -> NestedAction -> Model -> Model`. 

It has been suggested to me to "recurse" my way through this, but this just *feels* like a foot gun:

```elm
-- child
decode: Action -> Maybe String
decode act =
    case act of 
        ChildAction msg ->
            Just msg
        _ ->
            Nothing


-- parent
update act model = 
    case act of
        ChildAction  msg ->
            let
                model' = { model | child = Child.update msg model.child }
            in
                case Child.decode msg of
                    Nothing ->
                        model'
                    Just str ->
                        update (HandleChildAction str) model'
        HandleChildAction str ->
            { model | parentValue = manipulate str }

```

Is there a better way?

**Comment by pinx** [comment]
This has been bugging me as well. Hope it makes it into the tutorial one day.

**Comment by evancz** [comment]
Beginning of written advice in the right direction http://guide.elm-lang.org/reuse/

**Comment by seanhess** [comment]
@evancz The new section is soooo good. This week I'm training a team on Elm and have a huge section trying to convince people to reach for functions instead of TEA modules, and I'm glad to see you recommending the same thing.

**Comment by evancz** [comment]
Thanks! I was worried it was a bit too short, but I'm glad folks feel it's pointing them in the right direction :D
