### ISSUE TITLE
offline support

### ISSUE THREAD

**Issue by flip111** [evancz/elm-architecture-tutorial#31]
right now after donwloading the repo some additional stuff has to been downloaded for each example. Otherwise you will get a message like this

```
failed with 'FailedConnectionException2 "package.elm-lang.org" 80 False getAddrInfo: does not exist (Temporary failure in name resolution)' when sending request to
    <http://package.elm-lang.org/all-packages?elm-package-version=0.5.1&since=2015-09-11%2019%3A00%3A04.716736%20UTC>
```

Maybe an idea to download this all at once somehow? I wonder why each example needs to download code again actually.

**Comment by evancz** [comment]
This is the same as https://github.com/elm-lang/elm-repl/issues/54, so let's follow along over there. You currently need to download packages whenever you need them, same as with npm.
