### ISSUE TITLE
Start one server for all examples?

### ISSUE THREAD

**Issue by flip111** [evancz/elm-architecture-tutorial#32]
I thought i could be smart and start the server from the `examples` directory, so i can just browse to the individual examples. However the dependencies of program can not be found (even if stuff had been downloaded before). For example 1:

``
Error when searching for modules imported by module 'Main':
    Could not find module 'Counter'

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```

Also when example 2 tries to download stuff:
```
Downloading elm-lang/core
elm-make: elm-lang-core-5204441: rename: unsatisified constraints (Directory not empty)
```

**Comment by evancz** [comment]
Yeah, you cannot do that. You need to run the reactor from within `examples/1/` where the `elm-package.json` file lives. The problem is that different examples have modules with the same name. So it just does not work to think of them as a single project.
