### ISSUE TITLE
how to properly shutdown elm-reactor?

### ISSUE THREAD

**Issue by flip111** [evancz/elm-architecture-tutorial#33]
I try `cltr + z` to shut down elm-reactor, the prompt then becomes available again. But the process is still running and i have to go into htop to send SIGKILL (normal end does not work) before i can restart the server

**Comment by rgrempel** [comment]
I think you're asking a general UNIX question -- nothing specific to elm-reactor. `ctrl-z` sends SIGSTP, which only suspends the process (doesn't kill it), so I think what you're seeing is normal UNIX behaviour.
You might want `ctrl-c` instead?

**Comment by flip111** [comment]
Sorry i thought it was specific to the reactor. Thank you.
