### ISSUE TITLE
Debugger not available from example 1 onwards - missing file

### ISSUE THREAD

**Issue by netaisllc** [evancz/elm-architecture-tutorial#35]
Similar a bit to #34, but this command fails to render any output for me as early as example 1.

### http://localhost:8000/Main.elm?debug

giving a console error of "Failed to load resource: the server responded with a status of 500 (Internal Server Error) .... http://localhost:8000/_reactor/debug.js

This command renders the counter markup...

### http://localhost:8000/Main.elm

but this is probably not the experience intended for new elm explorers like me :)

``Ubuntu 14.04 LTS, 
node (via nvm) === iojs3.3, 
npm install -g elm``

**Comment by evancz** [comment]
It sounds like you installed with `npm`? If so, there is a note about setting your `ELM_HOME` variable to make certain assets available. I made it so we won't need that in the next release, but for now there is a packaging issue with the `npm` install route.

**Comment by netaisllc** [comment]
Hi Evan,

Yeah, used npm, and yeah I set the ELM_HOME env var.


BTW, I know the npm package is probably another developer's project, but
there is a bit of confusion introduced by it.

As you point out, a special environment var is need (which is no problem),
but messages from elm itself refer to PATH, which is different.
So, one (like me) wonders, 'do they mean add the location of elm to _both_
the PATH and ELM_HOME?"

Also, as a quick install, the npm guidance suggests using 'elm --help';
that always fails badly. While something like 'elm repl --home' works great.
I doubt that 'elm --help' even exists.

Gotta go, thanks. And I'm not giving up on this, there is too much goodness
in your work!

On Fri, Sep 18, 2015 at 1:34 AM, Evan Czaplicki <notifications@github.com>
wrote:

> It sounds like you installed with npm? If so, there is a note about
> setting your ELM_HOME variable to make certain assets available. I made
> it so we won't need that in the next release, but for now there is a
> packaging issue with the npm install route.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evancz/elm-architecture-tutorial/issues/35#issuecomment-141381415>
> .
>



-- 
*Kevin McGee*
415.886.7090 (*office*)
415-990-7169 (*mobile*)

/ Web application UI/UX
/ Technical writing
/ Project management

*Netais LLC - "Let's be clear"*

** Sending me a file?  *
   Just pop 'em into this free, secure webspace.
   No limits, and I'll receive them in no time at all.
   https://www.hightail.com/u/KevinMcGee363880
<http://dropbox.yousendit.com/KevinMcGee363880>

**Comment by netaisllc** [comment]
Here is what I see in terms of file locations:

cssian@cssianQOS:~$ echo $ELM_HOME
**/home/cssian/.nvm/versions/io.js/v3.3.0/lib/node_modules/elm/bin**


cssian@cssianQOS:**~/.nvm/versions/io.js/v3.3.0/lib/node_modules/elm/bin** $ ls -al
total 28
drwxrwxr-x 2 cssian cssian 4096 Sep 18 00:38 .
drwxrwxr-x 7 cssian cssian 4096 Sep 18 00:38 ..
-rwxrwxr-x 1 cssian cssian  211 May 28 00:25 elm
-rwxrwxr-x 1 cssian cssian  219 May 28 00:25 elm-make
-rwxrwxr-x 1 cssian cssian  222 May 28 00:25 elm-package
-rwxrwxr-x 1 cssian cssian  222 May 28 00:25 elm-reactor
-rwxrwxr-x 1 cssian cssian  219 May 28 00:25 elm-repl


cssian@cssianQOS:**~/.nvm/versions/io.js/v3.3.0/lib/node_modules/elm/share/reactor/_reactor** $ ls -al
total 424
drwxrwxr-x 3 cssian cssian   4096 Sep 18 00:38 .
drwxrwxr-x 3 cssian cssian   4096 Sep 18 00:38 ..
drwxrwxr-x 2 cssian cssian   4096 Sep 18 00:38 debugger
-rw-rw-r-- 1 cssian cssian 416005 Jul  4 07:24 debug.js
-rw-rw-r-- 1 cssian cssian   3007 May 28 01:28 wrench.png

Maybe somebody is misplacing **share/_reactor** as debug.js is what the browser complains about.

**Comment by netaisllc** [comment]
I **resolved the issue** (no console errors and the TTDBGR appears as expected!) with a sledgehammer:  

I copied the  directory 

**~/.nvm/versions/io.js/v3.3.0/lib/node_modules/elm/share/reactor/_reactor**

directly into the **examples/1** directory as such:

cssian@cssianQOS:~/Dropbox/Projects/dev_projects/elm-architecture-tutorial/examples/1$ ls -al
total 480
drwxrwxr-x  4 cssian cssian   4096 Sep 18 10:40 .
drwxrwxr-x 10 cssian cssian   4096 Sep 18 00:37 ..
-rw-rw-r--  1 cssian cssian    798 Sep 18 00:37 Counter.elm
-rw-rw-r--  1 cssian cssian 318856 Sep 18 10:39 elm.js
-rw-rw-r--  1 cssian cssian    472 Sep 18 00:37 elm-package.json
drwxrwxr-x  4 cssian cssian   4096 Sep 18 00:43 elm-stuff
-rw-r--r--  1 root   root   103614 Sep 18 10:37 favicon.ico
-rw-rw-r--  1 cssian cssian    159 Sep 18 00:37 Main.elm
**drwxr-xr-x  3 root   root     4096 Sep 18 10:40 _reactor**
-rw-rw-r--  1 cssian cssian    589 Sep 18 00:37 README.md

So it seems even more like a location assumption or miscue somewhere between elm, elm-reactor and the npm package...???

This can be closed now.

**Comment by netaisllc** [comment]
Resolved, the pathing to the Reactor folder was wrong.
Mostly this is a result of running Elm on Linux, installing node/npm via nvm.  Nvm places node in a different place than I expected.
