### ISSUE TITLE
comprehensive summary at the end

### ISSUE THREAD

**Issue by ccorcos** [evancz/elm-architecture-tutorial#38]
I followed most of this, but got kind of lost towards the end. Theres a lot of syntax sugar I'm unfamiliar with. I like how you built up to this point with a bunch of examples, but it would be cool if you ended with some highly-annotated code that explains everything inline, so I can really understand some of the syntax and the new types.

**Comment by lvrbrtsn** [comment]
I plan on working through the tutorials and writing blog posts about what confuses me and how to fix it. I will make pull requests if I have decent things to contribute.

**Comment by stevenmwade** [comment]
@ccorcos I agree because in the Elm docs it says this:

> Now again, it is very important that you read the Elm Architecture Tutorial because it describes how these building blocks work and how you can put them together into a nice modular architecture. I swear it will be faster to read through than to muddle around and try to sort it out by trial-and-error.

Now, maybe it's just me, but there are just code examples with no actual explanations as the docs seem to insinuate. The README just sends you back to where you came from and does not '[describe] how these building blocks work'.

**Comment by evancz** [comment]
http://guide.elm-lang.org/architecture/

If there is a link to not-that, can you point out exactly where? We can fix the link.

**Comment by evancz** [comment]
Also, I think OP is talking about when the walkthrough lived in this repo. It now lives in http://guide.elm-lang.org/architecture so I think it makes sense to retarget the issue to https://github.com/evancz/guide.elm-lang.org/ if it still stands.

**Comment by ccorcos** [comment]
I was talking about the 0.16 architecture. This is an old post at this point tho. No worries.
