### ISSUE TITLE
Why not "See code" instead of "Run locally"?

### ISSUE THREAD

**Issue by igrep** [evancz/elm-architecture-tutorial#39]
As a reader of the [README](https://github.com/evancz/elm-architecture-tutorial#readme),
I felt the link "Run locally" isn't named as it actually is:
When I was reading the README for the first time on my tablet,
I guessed it was to some URL like `localhost:8000/***`, which would never work on a tablet.
So I always used links in [examples](https://github.com/evancz/elm-architecture-tutorial/tree/master/examples), then wondered
:confused: "Why dosen't it have links to view the source directly?"

So, I suggest to change the link text of "Run locally" into "See code".
This sounds more naturally and show what actually it is.
Tell me your opinion.
If you approve, I'm going to fix.

**Comment by PBRT** [comment]
I agree, I always choose the wrong link, not very natural :) :+1:

**Comment by evancz** [comment]
Can you do a PR? I don't know exactly what you are referring to, but it seems like a relatively quick change that'll make things better.

**Comment by lvrbrtsn** [comment]
This issue was resolved right? It says click here to preview now.

**Comment by PBRT** [comment]
I just made a PR https://github.com/evancz/elm-architecture-tutorial/pull/53

**Comment by evancz** [comment]
Great, thank you!

**Comment by igrep** [comment]
@PBRT Thank you very much! :heart_eyes:
