### ISSUE TITLE
This is just a state machine!

### ISSUE THREAD

**Issue by sdegutis** [evancz/elm-architecture-tutorial#4]
@evancz I just realized, this is just the "state machine" pattern! That's why it was so familiar, why I like it so much, why it's so easy to grasp! We provide a model representing the sum of every possible state, a list of acceptable actions that our state machine can accept, a transition function that creates a new model based on an action, and a function to transform the model into something the user can see and interact with! If this is a reasonable interpretation, why not describe it this way somewhere on Elm's main home-page? Or at least in this tutorial? ~~(I don't understand why this `elm-architecture-tutorial` document isn't part of the official Elm documentation.)~~

**Comment by sdegutis** [comment]
> (I don't understand why this elm-architecture-tutorial document isn't part of the official Elm documentation.)

I remember now, you said it may soon be integrated into the main site.

**Comment by evancz** [comment]
I am not sure "state machine" is a term that everyone is familiar with, but I like that interpretation a lot.

I started using it a bit in [the union type docs](http://elm-lang.org/guide/model-the-problem#state-machines) and I think it works well. I'll think about using that term more often, but I'm not sure if it is a delightful topic for everyone :)
