### ISSUE TITLE
"Upper case characters are not allowed in package names."

### ISSUE THREAD

**Issue by danneu** [evancz/elm-architecture-tutorial#41]
Fresh install of elm-platform 0.16.0 on OSX 10.11.1 via the pkg installer.

Cloned this repo, tried to run it, and it complains about the "repository" value in elm-package.json being upper case:

    "repository": "https://github.com/USER/PROJECT.git",

Downcasing it satisfied the error, and I assume arose from a recent change in elm-package, but obviously it should be updated so that a fresh git clone is runnable.

**Comment by evancz** [comment]
Try `git pull` and see if you still run into this. I just updated this repo for 0.16.

**Comment by danneu** [comment]
Cool, seems to resolve both my issues at a glance in that `http://localhost:8000/Main.elm` now works for example 1 and renders a working counter.

Though when I add the ?debug flag I get some javascript errors in the console:

    [debug.js:9639] Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value (intermediate value)(intermediate value)(intermediate value)(intermediate value)(...) is not a function
    [Main.elm:11488] Uncaught TypeError: Elm.fullscreenDebug is not a function
