### ISSUE TITLE
"Error: Unable to find a set of packages that will work with your constraints."

### ISSUE THREAD

**Issue by danneu** [evancz/elm-architecture-tutorial#42]
(Fresh install of elm-platform 0.16.0 on OSX 10.11.1 via the pkg installer.)

Trying to navigate to the url served by elm-reactor or trying to `elm package install` fails with this error:

    danneu ~/Code/Elm/elm-architecture-tutorial/examples/1 master!
    $ elm package install

    Error: Unable to find a set of packages that will work with your constraints.

I'll keep digging to make sure it's not an issue with my environment.

**Comment by evancz** [comment]
Oops, need to update for 0.16, give me a few minutes!

**Comment by evancz** [comment]
Okay, should be fixed now. Try `git pull` and tell me if things start working!
