### ISSUE TITLE
error on first example: _U.list is not a function

### ISSUE THREAD

**Issue by ynimous** [evancz/elm-architecture-tutorial#43]
As per the instructions, I did:

     $ cd examples/1
     $ elm-reactor

But I got the following error in the browser:

    _U.list is not a function

    Open the developer console for more details.

**Comment by paparga** [comment]
Just filling the same issue: 

I followed the instructions:
https://github.com/evancz/elm-architecture-tutorial/tree/master/examples/1

http://localhost:8000/Main.elm runs, but when I try http://localhost:8000/Main.elm?debug I get this error:

![image](https://cloud.githubusercontent.com/assets/2799637/11319680/11183c06-905e-11e5-8efd-b78126882b63.png)

I'm using elm 0.16 installed via npm

**Comment by evancz** [comment]
There is a bug with the `?debug` flag in 0.16, so I went through just now and changed all the directions to point at the link without that. Currently working on a proper fix though!
