### ISSUE TITLE
Potential issue with multiple Ticks in example 8?

### ISSUE THREAD

**Issue by hayohayo** [evancz/elm-architecture-tutorial#44]
(First of all, I can't seem to be able to run example 8 since I've updated to 0.16, so had to disable DanDanDan/Easing).

In any case, I am looking at `update` function and to me it seems that there's is a potential problem with how `Spin` action is checked. And if state is `Nothing`, a `Tick` action is sent, but `model` is not updated. Is it possible that multiple `Spin`s arrive before the first `Tick`?

I've tried to simulate this by sending `Spin'` from `onClick`, which in turn sends 2 `Spin`s:

```
update msg model =
  case msg of
    Spin' ->
      ( model, Effects.batch [Effects.task (Task.succeed Spin), Effects.task (Task.succeed Spin)] )
    ...
```

Now each square turns all 180 degrees. Should not there be a special `PreSpin` state? Or maybe we can get current time instantaneously somehow?

**Comment by evancz** [comment]
Having subscriptions in 0.17 should make it much harder to have "simultaneous" animations going.
