### ISSUE TITLE
bind: failed (Permission denied (WSAEACCESS))

### ISSUE THREAD

**Issue by ManuelDeLeon** [evancz/elm-architecture-tutorial#46]
This happens when the default port 8000 is already taken by another program. In the spirit of friendlier messages elm-reactor should say something like "Default port 8000 is already taken please try another port with 'elm-reactor -p 80801".

**Comment by evancz** [comment]
Makes sense. Looks like it's the same as https://github.com/elm-lang/elm-reactor/issues/108 so I am going to close here. Can you tell folks the root problem on that issue and suggest that we have a nicer error message?

(I think the error messages are nicer already on mac and linux, which may explain why I did not see this earlier)
