### ISSUE TITLE
multiple arguments in type annotations never explained

### ISSUE THREAD

**Issue by faceyspacey** [evancz/elm-architecture-tutorial#55]
I couldn't find anywhere the explanation of how multiple arguments are separated by `->` followed by the return, eg:

```
diamond: Color -> Float -> Form
```

It's not explained here:
http://elm-lang.org/guide/model-the-problem#contracts

I didn't figure it out until I got to the "Type Annotations" section of this 3rd party article:
https://pragmaticstudio.com/blog/2014/12/19/getting-started-with-elm

My experience was that I was trying to imagine various things that could be going on, and the best I came up with was that type annotations were describing functions that take a single argument which is a function that itself returns a function and so on lol. I thought it was recursively describing the types of passed in functions (and their parameters + returns). 

I put a lot of mental work into trying to figure out what--my recommendation is--should be described in the "Model the Problem" article and re-iterated in this tutorial. 

..my 2 cents

**Comment by evancz** [comment]
This is explained in the new http://guide.elm-lang.org/, specifically in http://guide.elm-lang.org/types/reading_types.html

Hopefully that helps
