### ISSUE TITLE
Context signal address with effects

### ISSUE THREAD

**Issue by ilkosta** [evancz/elm-architecture-tutorial#74]
Hi,
reading the tutorial I have some doubts regarding the use of a Context to propagate a signal to a parent component (as in example 4) where the component use `Effects API`.

I'm thinking to a component-form with Actions like `Save` | `Error` | `Saved`, that can be created dynamically and deleted only after a success save.

What is the right way to go? create a customized update to send the remove action to the parent component?

**Comment by evancz** [comment]
I don't fully understand the question, but I don't think this is the right way to go. Example 4 was not a good example of how things should go. I am working on updating all the examples for 0.17 so I'll have something about that soon.
