### ISSUE TITLE
[Question] How Elm handles the case in Example 2 where there are two same components underneath ?

### ISSUE THREAD

**Issue by haohcraft** [evancz/elm-architecture-tutorial#76]
This is a newbie's question.
I am curious how Elm differentiates the two same components underneath. Or how does it implement the `namespace` concept here?
Any extended source about this topic?
Thanks in advance.

**Comment by jvoigtlaender** [comment]
Questions are better asked on the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss).
