### ISSUE TITLE
Error: Unable to find a set of packages that will work with your constraints.

### ISSUE THREAD

**Issue by ajlai** [evancz/elm-architecture-tutorial#81]
New install on OSX, version 0.17.0.

Running into this issue:
```
[anthony@ambp] ~/dev/elm-architecture-tutorial/examples/1 master 2016-05-11 22:12:13 > elm package install

Error: Unable to find a set of packages that will work with your constraints.
```
 
Is this similar to https://github.com/evancz/elm-architecture-tutorial/issues/42 ?

**Comment by mordrax** [comment]
what's in your elm-package.json? I had some older elm-html, elm-core and it doesn't like it

**Comment by acurry** [comment]
I ran into the same issue. From what I can tell, this repo hasn't been updated yet to use elm `v0.17`. The [v0.17 upgrade guide](https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.17.md) has sample code written in `v0.16` that resemble the examples in this repo and would need to be updated.

**Comment by ajlai** [comment]
@mordrax this happened to me with a fresh pull of master. This is the one I had: https://github.com/evancz/elm-architecture-tutorial/blob/de5682a5a8e4459aed4637533adb25e462f8a2ae/examples/1/elm-package.json

@acurry I think you are right, if I'm reading https://github.com/evancz/elm-architecture-tutorial/blob/de5682a5a8e4459aed4637533adb25e462f8a2ae/examples/1/elm-package.json#L15 correctly.

**Comment by mordrax** [comment]
Yes, the examples are not yet updated. I had created my project instead of
cloning it.

Looks like you just need to remove start-app and update the other packages
as per the 0.17 upgrade path.

I'm just starting on the examples myself and am manually converting them to
0.17 as I go. Takes a bit more thought but helps the learning process. It's
starting to get a bit crazy with example 4.

**Comment by evancz** [comment]
It should be updated to 0.17 as of yesterday.

Example 4 was a bad example. Not worth updating. People should not write code that way.
