### ISSUE TITLE
Elm Tutorial (fist project setup)

### ISSUE THREAD

**Issue by krzychukula** [evancz/elm-architecture-tutorial#84]
Is there anywhere official Elm tutorial?
Something more hands-on than http://guide.elm-lang.org/index.html?

What I'm looking for is something like:
1. Install elm from here: http://elm-lang.org/install
2. mkdir hello-world
3. generate new project?
4. crate file Main.elm
5. write: http://elm-lang.org/examples/hello-html in the file
6. run the file somehow

I was expecting something like this on: http://elm-lang.org/get-started but there is too much stuff there and the best things I've found while skimming were to clone examples and I don't want to do that.

If I've missed this kind of tutorial I would appreciate if you can point it out to me :)

**Comment by simonewebdesign** [comment]
From a quick search I found this kind of tutorial [here](http://www.elm-tutorial.org/en/01-foundations/01-hello.html) and [here](https://www.gitbook.com/book/sporto/elm-tutorial/details). But I agree it would be nice to have something like that in the official website.

By the way, about generating a project, there's a tool I've built, [elm-new](https://github.com/simonewebdesign/elm-new), that gives you that kind of experience. Basically you run:

``` bash
mkdir hello-world
cd hello-world
elm new --beginner

# or just:
elm new hello-world --beginner
```

And it generates a basic project using `Html.App.beginnerProgram`.

Not exactly what you're looking for, but I'm thinking about adding a `--hello-world` option. Maybe it could also point people to the official guide or something. What do you think?

**Comment by krzychukula** [comment]
@simonewebdesign I like both elm-new and http://www.elm-tutorial.org/en/01-foundations/01-hello.html. Thanks

**Comment by pirj** [comment]
Hey @krzychukula 
[Contribution checklist](https://github.com/process-bot/contribution-checklist/blob/master/issues.md) mentions that issues are for bugs, and if you have questions, ask them on a [community forum][http://elm-lang.org/community]. Folks are friendly and happy to help!
Do you think it makes sense to keep this issue open?
