### ISSUE TITLE
I cannot find module 'Counter'.

### ISSUE THREAD

**Issue by frranck** [evancz/elm-architecture-tutorial#88]
Hi,
I'm running into this problem when loading  "1-counter-pair.elm"
```

 I cannot find module 'Counter'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json

```
Any idea ?

**Comment by evancz** [comment]
How are you trying to compile things? Are you running `elm-reactor` from the root of the project, or from inside the `nesting/` directory?

Also, I'd recommend asking about this on [the Elm slack](http://elmlang.herokuapp.com/). They can help you work through this faster and figure out if any changes are needed here.

**Comment by frranck** [comment]
@evancz  I'm running elm-reactor from the root of the project

**Comment by evancz** [comment]
The `nesting/` directory no longer exists, so this is resolved in that it cannot be reproduced anymore.
