### ISSUE TITLE
Do effectful components count as part of the Elm Architecture?

### ISSUE THREAD

**Issue by TheSeamau5** [evancz/elm-architecture-tutorial#9]
So, I have the use case where I have a component that does some animations. These animations involve timing. 

An example of this is the material design components: 
https://material.angularjs.org/#/demo/material.components.button

In material design, when you click a button, you have this ripple effect. The effect goes as follows:

1. Start as a small circle 
2. Grow to fill the container 
3. Wait a few milliseconds
4. Fade away

Conceptually, in Elm, you could implement this as two components: `Button` and `Ripple`.

You'd like to send the `Button` an action like: 

```elm
ClickAt (Int, Int)
```

and then that `Button` would send an action to the `Ripple` like : 

```elm
Animate (Int, Int) Float
```

where you pass in the starting position of the ripple effect and the maximum size that effect would have.

The problem, is, how to implement this animation in Elm? The problem is that a single action is expected to produce several actions that are separated by a time interval.

#### Solution 1: Do it in CSS 

You could implement this in CSS with CSS Animations and just change a "class" in Elm. Certainly, this follows some of the best practices, but then these things are harder to share. 

**Pros :** 

1. Straightforward to implement
2. Putting styles in a stylesheet follows best practices

**Cons :** 

1. You must include a separate stylesheet whenever you want to use a component, making it harder to have components that depend on other components that depend on other components especially if at each level of the dependency there's a different author / package.
2. CSS is a different language. With inline styles, you get to pair the awesomeness of Elm and all of its libraries and functionality with CSS. For example, you can have functions that produce new styles and variables to hold different values (no need to use a pre-processor or something).
3. Harder to maintain. Any modification of the component requires to make modifications in two different languages and keeping everything in sync is challenging.

#### Solution 2: Make the component effectful

Instead of having the view function for the `Button` look like this

```elm
view : Address Action -> State -> Html
```

it would instead look like this:

```elm
view : Address (Task error ()) -> Address Action -> State -> Html
```

And, instead of sending one action to the `Ripple`, you would send multiple actions interspersed by timers.

```elm
rippleAnimation : Address Ripple.Action -> (Int, Int) -> Float -> Task error ()
rippleAnimation address startingPosition maxRadius = 
  send address (StartAt startingPosition)
    `andThen` \_ -> send address (GrowTo maxRadius)
    `andThen` \_ -> sleep 100
    `andThen` \_ -> send address FadeAway
```

And then, in the `Button.view` you'd do something like:

```elm
onButtonClick taskAddress (rippleAnimation rippleAddress)
```

(we can assume `onButtonClick` gets the necessary info from the DOM and passes it to `rippleAnimation`)

**Pros :** 

1. No need to go into CSS. Animation is fully handled in Elm. No need for extra stylesheet. This also means that you can see the results in elm-reactor as opposed to in some html file.
2. Easier to maintain. Everything is self-contained in Elm and subject to all the guarantees Elm provides.
3. This solution is extensible to arbitrary effects. This means you can have a component that display a map from google maps or an autocompleter that can fetch its data from the web, etc...
[You can see here for real-life examples of effectful components](https://customelements.io/)

**Cons :** 

1. Components now require opening a port for them to work. Ideally, if you manage to make sure all your tasks are of the same type, then you could jam everything into a single address and thus need to open only one port. But this also means that leaving out the port does not guarantee that a button will work properly. 

2. A component which could be effect-free is now effectful just for the sake of an animation. This means that for an animation, this component has been granted the potential capability of getting data from or sending data to the internet, etc... It does feel a bit heavy handed if your goal is to just animate something.

So, my question is, do these things still count as part of the Elm Architecture? Is having components that can send tasks a good thing?

**Comment by evancz** [comment]
I think the real question might be "how do we do animations in a good way?" I know elm-d3 is not up to date at all, but that direction would be my solution 3.

As for tasks from components, I'd generally stay away from it. A task tells you nothing about what is actually going to happen, so any ability to cache or batch stuff goes away, no analysis can be done once you go into tasks. If you just pass out data and have some interpreter that'll do what the data says, you can be much fancier. Let's say you have 5 animations stacked up. With tasks, they just hopefully work out okay. With an interpreter, you can decide to accelerate things or skipped things if stuff starts piling up. I think this is true for animations, but I suspect it's the general pattern when you feel tempted to put tasks in components.

**Comment by evancz** [comment]
Also, I don't think there's such a thing as "an effectful component" in Elm. Even when you are passing out tasks, there are no effects. When you do want to allow some effects, I think a reasonable API is to have something like this:

```elm
type Request

update : Action -> Model -> (Model, Maybe Request)

run : Request -> Task e a    -- where e and a are filled in as appropriate
```

This means someone higher up the chain can turn it to tasks when it's the right time. And if you want to add something like this it's doable:

```elm
batch : List Request -> Request
```

Once we have concurrency, I suspect we can do fancier things with "runners" that manage any batching or caching or whatever and you just have to pipe in the requests.

**Comment by TheSeamau5** [comment]
This makes a lot of sense. Basically, the top-most component would be like the grand central dispatcher that sends all the queries and relays everything. But with this model, it only cares what was sent from one level down. Cool!

This also guarantees that the whole thing is serializable, including the request. This is a really important point I missed out. One of the approaches I was considering was to sneak in the address in the component state. But this would break everything cuz you want the state to be serializable. You'd like to be able to grab it, cache it, send it over the wire, etc...

The other approach I was considering is having one big address for all the tasks and you could get at it cuz it was defined somewhere in a library. All the components send tasks to that one mailbox defined somewhere. I think it sounds alright until we get to your point about batching requests. Basically, if all the components just wildly start sending tasks, you loose control of what did what when. It's like, some stupid button 10 levels down made a task that is looping forever because it was passed in a negative number or whatever and now the whole thing doesn't work. Whereas if you deal just with these requests, the top-most component or the main view function or whatever will get to control what to do exactly. It could even group these requests, filter out the redundant ones, etc... With a good enough system, you could even enforce that the same request never gets made twice. 
-------

Although, it did give me pause to think about animations. This is an aside, but I think one way this could be done is by using something like `Time.fps` or `AnimationFrame.frame`, to generate a counter. Imagine a counter that starts at one and increments every 16 milliseconds. This counter could represent the current frame (the actual value of which may or may not be useful cuz we could just do modulo or whatever). 

You can then send this value down the component hierarchy to all the components that need animation. Like, suppose they just all have a field called `currentAnimationFrame`.

Then, animations would be simple. Either it's something like the ink ripple effect, in which case you can use canvas and that works well. (actually, that's how the Polymer guys implemented it)
Or, we want to move or resize a component, in which case we do the animation by modifying CSS dynamically via inline styles. No CSS Transitions or Animations. Like, if you wanna move a component, you do it by defining the dimensions and position of a component in Elm and then you take into account the current animation frame to figure exactly what these values must be.

This is why I came up with that "History/Timeline" thing. The idea is to explore a way of defining keyframe animations as "timelines". An animation is just a set of keyframes (the individual frames) and there's a way to transition from one frame to the other. Then you can connect multiple animations together to form an animation group and even define how to transition from one to the other. 

Aside from that, I think that D3 would be a cool option, although I'm no expert on D3 so I can't say much about it.

**Comment by evancz** [comment]
I think this is covered by the new elm-effects stuff? I'm closing on that supposition. Please reopen if not!

**Comment by TheSeamau5** [comment]
I think it is covered. As for animations, I think there's more work to be done but for the moment, effects seem to be fully covered.

**Comment by evancz** [comment]
Okay, and check out the new version of example 8. @Dandandan cleaned it up quite a bit.

I still think the batching of animations needs special considerations outside the scope of the basic `elm-effects` package. I suspect we will get a fan out of packages like that for things like GraphQL and batched animations and such, after which we can bring it all back into a centralized place.

**Comment by TheSeamau5** [comment]
Looks good and clean. :D I like the direction this has taken.

Yeah, I think that the day we'll start having to deal with things like GraphQL we'll learn about how to deal with non-task based effects, which could then re-inform the API in a positive way. Anyways, good job. Looks super usable and very little boilerplate added to the Elm Architecture in general.
