### ISSUE TITLE
Cannot find variable 'Html.program'

### ISSUE THREAD

**Issue by zwhitchcox** [evancz/elm-architecture-tutorial#92]
Brand new to elm, and I just copied the dice example, and it says `Cannot find variable Html.program`...is this package just outdated or something?

**Comment by zwhitchcox** [comment]
Sooo...looking at the [Html.App docs](http://package.elm-lang.org/packages/elm-lang/html/1.1.0/Html-App) it tells me to look her....so....yeah haha

**Comment by TaylorDennisLee** [comment]
@zwhitchcox what was the solution?
