### ISSUE TITLE
CORS error in HTTP example.

### ISSUE THREAD

**Issue by jbsaff** [evancz/elm-architecture-tutorial#97]
Seems related to the change in https://github.com/evancz/elm-architecture-tutorial/commit/30ce490b66c3b030e5580f5c6328ba7cf7b04e6b

I've copied the example directly from the repo here and get an error:

> XMLHttpRequest cannot load https://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&tag=cats. The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://localhost:8000' is therefore not allowed access.

Is there anything that can be done to correct the tutorial? My very brief investigation indicated this was likely a misconfiguration on gliphy's side, so maybe a different example is needed.

**Comment by evancz** [comment]
It is this https://github.com/Giphy/GiphyAPI/issues/105

It has been reported already https://github.com/elm-lang/elm-lang.org/issues/657 but it looks like the fix on their side is taking longer than estimated. I think it'd be lame to have to redo the example, but if there's some other URL we can get random gifs from, I'm open to switching.

**Comment by jbsaff** [comment]
Apparently I just picked the wrong day. Looks like they're getting the fix rolled out today, because the demo is working again. Closing.

**Comment by evancz** [comment]
Great to hear, and sorry for the trouble!
